//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AllstarFull
{
    public int ID { get; set; }
    public string playerID { get; set; }
    public string yearID { get; set; }
    public string gameNum { get; set; }
    public string gameID { get; set; }
    public string teamID { get; set; }
    public string lgID { get; set; }
    public string GP { get; set; }
    public string startingPos { get; set; }
}

public partial class Appearance
{
    public int ID { get; set; }
    public string yearID { get; set; }
    public string teamID { get; set; }
    public string lgID { get; set; }
    public string playerID { get; set; }
    public string G_all { get; set; }
    public string GS { get; set; }
    public string G_batting { get; set; }
    public string G_defense { get; set; }
    public string G_p { get; set; }
    public string G_c { get; set; }
    public string G_1b { get; set; }
    public string G_2b { get; set; }
    public string G_3b { get; set; }
    public string G_ss { get; set; }
    public string G_lf { get; set; }
    public string G_cf { get; set; }
    public string G_rf { get; set; }
    public string G_of { get; set; }
    public string G_dh { get; set; }
    public string G_ph { get; set; }
    public string G_pr { get; set; }
}

public partial class AwardsManager
{
    public int ID { get; set; }
    public string managerID { get; set; }
    public string awardID { get; set; }
    public string yearID { get; set; }
    public string lgID { get; set; }
    public string tie { get; set; }
    public string notes { get; set; }
}

public partial class AwardsPlayer
{
    public int ID { get; set; }
    public string playerID { get; set; }
    public string awardID { get; set; }
    public string yearID { get; set; }
    public string lgID { get; set; }
    public string tie { get; set; }
    public string notes { get; set; }
}

public partial class AwardsShareManager
{
    public int ID { get; set; }
    public string awardID { get; set; }
    public string yearID { get; set; }
    public string lgID { get; set; }
    public string managerID { get; set; }
    public string pointsWon { get; set; }
    public string pointsMax { get; set; }
    public string votesFirst { get; set; }
}

public partial class AwardsSharePlayer
{
    public int ID { get; set; }
    public string awardID { get; set; }
    public string yearID { get; set; }
    public string lgID { get; set; }
    public string playerID { get; set; }
    public string pointsWon { get; set; }
    public string pointsMax { get; set; }
    public string votesFirst { get; set; }
}

public partial class Batting
{
    public int ID { get; set; }
    public string playerID { get; set; }
    public string yearID { get; set; }
    public string stint { get; set; }
    public string teamID { get; set; }
    public string lgID { get; set; }
    public string G { get; set; }
    public string G_batting { get; set; }
    public string AB { get; set; }
    public string R { get; set; }
    public string H { get; set; }
    public string C2B { get; set; }
    public string C3B { get; set; }
    public string HR { get; set; }
    public string RBI { get; set; }
    public string SB { get; set; }
    public string CS { get; set; }
    public string BB { get; set; }
    public string SO { get; set; }
    public string IBB { get; set; }
    public string HBP { get; set; }
    public string SH { get; set; }
    public string SF { get; set; }
    public string GIDP { get; set; }
    public string G_old { get; set; }
}

public partial class BattingPost
{
    public int ID { get; set; }
    public string yearID { get; set; }
    public string round { get; set; }
    public string playerID { get; set; }
    public string teamID { get; set; }
    public string lgID { get; set; }
    public string G { get; set; }
    public string AB { get; set; }
    public string R { get; set; }
    public string H { get; set; }
    public string C2B { get; set; }
    public string C3B { get; set; }
    public string HR { get; set; }
    public string RBI { get; set; }
    public string SB { get; set; }
    public string CS { get; set; }
    public string BB { get; set; }
    public string SO { get; set; }
    public string IBB { get; set; }
    public string HBP { get; set; }
    public string SH { get; set; }
    public string SF { get; set; }
    public string GIDP { get; set; }
}

public partial class HallOfFame
{
    public int ID { get; set; }
    public string hofID { get; set; }
    public string yearid { get; set; }
    public string votedBy { get; set; }
    public string ballots { get; set; }
    public string needed { get; set; }
    public string votes { get; set; }
    public string inducted { get; set; }
    public string category { get; set; }
    public string needed_note { get; set; }
}

public partial class Manager
{
    public int ID { get; set; }
    public string managerID { get; set; }
    public string yearID { get; set; }
    public string teamID { get; set; }
    public string lgID { get; set; }
    public string inseason { get; set; }
    public string G { get; set; }
    public string W { get; set; }
    public string L { get; set; }
    public string rank { get; set; }
    public string plyrMgr { get; set; }
}

public partial class ManagersHalf
{
    public int ID { get; set; }
    public string managerID { get; set; }
    public string yearID { get; set; }
    public string teamID { get; set; }
    public string lgID { get; set; }
    public string inseason { get; set; }
    public string half { get; set; }
    public string G { get; set; }
    public string W { get; set; }
    public string L { get; set; }
    public string rank { get; set; }
}

public partial class Master
{
    public int ID { get; set; }
    public string lahmanID { get; set; }
    public string playerID { get; set; }
    public string managerID { get; set; }
    public string hofID { get; set; }
    public string birthYear { get; set; }
    public string birthMonth { get; set; }
    public string birthDay { get; set; }
    public string birthCountry { get; set; }
    public string birthState { get; set; }
    public string birthCity { get; set; }
    public string deathYear { get; set; }
    public string deathMonth { get; set; }
    public string deathDay { get; set; }
    public string deathCountry { get; set; }
    public string deathState { get; set; }
    public string deathCity { get; set; }
    public string nameFirst { get; set; }
    public string nameLast { get; set; }
    public string nameNote { get; set; }
    public string nameGiven { get; set; }
    public string nameNick { get; set; }
    public string weight { get; set; }
    public string height { get; set; }
    public string bats { get; set; }
    public string throws { get; set; }
    public string debut { get; set; }
    public string finalGame { get; set; }
    public string college { get; set; }
    public string lahman40ID { get; set; }
    public string lahman45ID { get; set; }
    public string retroID { get; set; }
    public string holtzID { get; set; }
    public string bbrefID { get; set; }
}

public partial class Pitching
{
    public int ID { get; set; }
    public string playerID { get; set; }
    public string yearID { get; set; }
    public string stint { get; set; }
    public string teamID { get; set; }
    public string lgID { get; set; }
    public string W { get; set; }
    public string L { get; set; }
    public string G { get; set; }
    public string GS { get; set; }
    public string CG { get; set; }
    public string SHO { get; set; }
    public string SV { get; set; }
    public string IPouts { get; set; }
    public string H { get; set; }
    public string ER { get; set; }
    public string HR { get; set; }
    public string BB { get; set; }
    public string SO { get; set; }
    public string BAOpp { get; set; }
    public string ERA { get; set; }
    public string IBB { get; set; }
    public string WP { get; set; }
    public string HBP { get; set; }
    public string BK { get; set; }
    public string BFP { get; set; }
    public string GF { get; set; }
    public string R { get; set; }
    public string SH { get; set; }
    public string SF { get; set; }
    public string GIDP { get; set; }
}

public partial class PitchingPost
{
    public int ID { get; set; }
    public string playerID { get; set; }
    public string yearID { get; set; }
    public string round { get; set; }
    public string teamID { get; set; }
    public string lgID { get; set; }
    public string W { get; set; }
    public string L { get; set; }
    public string G { get; set; }
    public string GS { get; set; }
    public string CG { get; set; }
    public string SHO { get; set; }
    public string SV { get; set; }
    public string IPouts { get; set; }
    public string H { get; set; }
    public string ER { get; set; }
    public string HR { get; set; }
    public string BB { get; set; }
    public string SO { get; set; }
    public string BAOpp { get; set; }
    public string ERA { get; set; }
    public string IBB { get; set; }
    public string WP { get; set; }
    public string HBP { get; set; }
    public string BK { get; set; }
    public string BFP { get; set; }
    public string GF { get; set; }
    public string R { get; set; }
    public string SH { get; set; }
    public string SF { get; set; }
    public string GIDP { get; set; }
}

public partial class Salary
{
    public int ID { get; set; }
    public string yearID { get; set; }
    public string teamID { get; set; }
    public string lgID { get; set; }
    public string playerID { get; set; }
    public string salary1 { get; set; }
}

public partial class School
{
    public int ID { get; set; }
    public string schoolID { get; set; }
    public string schoolName { get; set; }
    public string schoolCity { get; set; }
    public string schoolState { get; set; }
    public string schoolNick { get; set; }
}

public partial class SchoolsPlayer
{
    public int ID { get; set; }
    public string playerID { get; set; }
    public string schoolID { get; set; }
    public string yearMin { get; set; }
    public string yearMax { get; set; }
}

public partial class SeriesPost
{
    public int ID { get; set; }
    public string yearID { get; set; }
    public string round { get; set; }
    public string teamIDwinner { get; set; }
    public string lgIDwinner { get; set; }
    public string teamIDloser { get; set; }
    public string lgIDloser { get; set; }
    public string wins { get; set; }
    public string losses { get; set; }
    public string ties { get; set; }
}

public partial class Team
{
    public int ID { get; set; }
    public string yearID { get; set; }
    public string lgID { get; set; }
    public string teamID { get; set; }
    public string franchID { get; set; }
    public string divID { get; set; }
    public string Rank { get; set; }
    public string G { get; set; }
    public string Ghome { get; set; }
    public string W { get; set; }
    public string L { get; set; }
    public string DivWin { get; set; }
    public string WCWin { get; set; }
    public string LgWin { get; set; }
    public string WSWin { get; set; }
    public string R { get; set; }
    public string AB { get; set; }
    public string H { get; set; }
    public string C2B { get; set; }
    public string C3B { get; set; }
    public string HR { get; set; }
    public string BB { get; set; }
    public string SO { get; set; }
    public string SB { get; set; }
    public string CS { get; set; }
    public string HBP { get; set; }
    public string SF { get; set; }
    public string RA { get; set; }
    public string ER { get; set; }
    public string ERA { get; set; }
    public string CG { get; set; }
    public string SHO { get; set; }
    public string SV { get; set; }
    public string IPouts { get; set; }
    public string HA { get; set; }
    public string HRA { get; set; }
    public string BBA { get; set; }
    public string SOA { get; set; }
    public string E { get; set; }
    public string DP { get; set; }
    public string FP { get; set; }
    public string name { get; set; }
    public string park { get; set; }
    public string attendance { get; set; }
    public string BPF { get; set; }
    public string PPF { get; set; }
    public string teamIDBR { get; set; }
    public string teamIDlahman45 { get; set; }
    public string teamIDretro { get; set; }
}

public partial class TeamsFranchis
{
    public int ID { get; set; }
    public string franchID { get; set; }
    public string franchName { get; set; }
    public string active { get; set; }
    public string NAassoc { get; set; }
}

public partial class TeamsHalf
{
    public int ID { get; set; }
    public string yearID { get; set; }
    public string lgID { get; set; }
    public string teamID { get; set; }
    public string Half { get; set; }
    public string divID { get; set; }
    public string DivWin { get; set; }
    public string Rank { get; set; }
    public string G { get; set; }
    public string W { get; set; }
    public string L { get; set; }
}
